# -*- coding: utf-8 -*-
"""Backend code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QMlWkS9aeRiyy3OueFieg97J-xDVGJwt
"""

!pip install fastapi uvicorn pyngrok python-multipart
!pip install -q detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu118/torch2.0/index.html

from google.colab import drive
drive.mount('/content/drive')

!git clone https://github.com/facebookresearch/detectron2 detectron2_repo
!pip install -e detectron2_repo

!pip install fastapi uvicorn pyngrok python-multipart opencv-python-headless joblib scikit-learn pandas matplotlib xgboost --quiet
!pip install detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu118/torch2.0/index.html --quiet

from collections import defaultdict
from datetime import datetime
import sqlite3
import json

!pip install fastapi uvicorn pyngrok python-multipart opencv-python-headless joblib scikit-learn pandas matplotlib xgboost --quiet
!pip install detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu118/torch2.0/index.html --quiet

!pip install pyngrok

from torchvision.ops import nms

from fastapi import FastAPI

!pip install email-validator

"""#Final Execution

# damage, severity, cost prediction weights
"""

# === MODEL SETUP ===
from detectron2.engine import DefaultPredictor
from detectron2.config import get_cfg
from detectron2 import model_zoo
from detectron2.data import MetadataCatalog
import joblib, torch

# Load XGBoost + Encoder
model = joblib.load("/content/drive/MyDrive/repair_model_severe/car_model_encoder.pkl")
encoder = joblib.load("/content/drive/MyDrive/repair_model_severe/repair_cost_model.pkl")

# Damage model setup
cfg_parts = get_cfg()
cfg_parts.merge_from_file(model_zoo.get_config_file("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"))
cfg_parts.MODEL.WEIGHTS = "/content/drive/MyDrive/damage_model.pth"
cfg_parts.MODEL.ROI_HEADS.NUM_CLASSES = 11
cfg_parts.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5
cfg_parts.MODEL.DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
predictor_parts = DefaultPredictor(cfg_parts)

# Severity model setup
cfg_sev = get_cfg()
cfg_sev.merge_from_file(model_zoo.get_config_file("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"))
cfg_sev.MODEL.WEIGHTS = "/content/drive/MyDrive/severity_model (1).pth"
cfg_sev.MODEL.ROI_HEADS.NUM_CLASSES = 3
cfg_sev.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5
cfg_sev.MODEL.DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
predictor_sev = DefaultPredictor(cfg_sev)

# Set metadata
metadata_parts = MetadataCatalog.get("car_part_val")
metadata_parts.thing_classes = ['car', 'RunningBoard-Dent', 'Sidemirror-Damage', 'damaged-head-light', 'damaged-hood', 'damaged_bumper', 'damaged_door', 'damaged_fender', 'damaged_trunk', 'missing_grille', 'shattered-glass']

metadata_sev = MetadataCatalog.get("car_severity_val")
metadata_sev.thing_classes = ["minor", "moderate", "severe"]

"""#schema for history of the images  uploaded  """

import os
import sqlite3
from datetime import datetime
import json

UPLOAD_DIR = "/content/uploads"
os.makedirs(UPLOAD_DIR, exist_ok=True)

DB_PATH = os.path.join(UPLOAD_DIR, "history.db")
conn = sqlite3.connect(DB_PATH, check_same_thread=False)
cursor = conn.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS predictions (
    id TEXT PRIMARY KEY,
    filename TEXT,
    car_model TEXT,
    predicted_cost REAL,
    manual_cost REAL,
    breakdown_json TEXT,
    img_parts_path TEXT,
    img_severity_path TEXT,
    timestamp TEXT
)
""")
conn.commit()

"""#claims schema"""

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, EmailStr
from typing import Optional
import sqlite3
import os
from datetime import datetime
from pyngrok import ngrok
import uvicorn
import nest_asyncio

app = FastAPI()

from fastapi.middleware.cors import CORSMiddleware

# Enable CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # 👈 Allow all frontend URLs (React)
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ✅ Database path setup
UPLOAD_DIR = "/content/uploads"
os.makedirs(UPLOAD_DIR, exist_ok=True)
DB_PATH = os.path.join(UPLOAD_DIR, "history.db")

# ✅ Create table
conn = sqlite3.connect(DB_PATH)
cursor = conn.cursor()
cursor.execute("""
CREATE TABLE IF NOT EXISTS claims (
    id INTEGER PRIMARY KEY AUTOINCREMENT,

    -- Step 1
    policy_no TEXT,
    vehicle_make TEXT,
    vehicle_model TEXT,
    vehicle_color TEXT,
    engine_no TEXT,
    chassis_no TEXT,
    registration_no TEXT,
    year_of_manufacture INTEGER,
    policy_start_date TEXT,
    policy_end_date TEXT,
    vehicle_start_date TEXT,
    vehicle_end_date TEXT,
    claim_count INTEGER,
    claim_intimation_amount REAL,
    claim_paid_amount REAL,
    deductible_amount REAL,
    outstanding REAL,

    -- Step 2
    claim_type TEXT,
    branch TEXT,
    incident_date_time TEXT,
    incident_place TEXT,
    current_location TEXT,
    circumstances TEXT,
    missing_parts_details TEXT,
    workshop_type TEXT,
    vehicle_type TEXT,
    workshop_name TEXT,
    vehicle_availability TEXT,
    date_field TEXT,

    -- Step 3
    relation_with_insured TEXT,
    contact_person_name TEXT,
    contact_number TEXT,
    email TEXT,
    remarks TEXT,
    remarks2 TEXT,
    date_time TEXT
)
""")
conn.commit()
conn.close()

# ✅ Pydantic model
class Claim(BaseModel):
    # Step 1
    policy_no: str
    vehicle_make: str
    vehicle_model: str
    vehicle_color: Optional[str] = None
    engine_no: Optional[str] = None
    chassis_no: Optional[str] = None
    registration_no: Optional[str] = None
    year_of_manufacture: Optional[int] = None
    policy_start_date: Optional[str]
    policy_end_date: Optional[str]
    vehicle_start_date: Optional[str]
    vehicle_end_date: Optional[str]
    claim_count: Optional[int] = 0
    claim_intimation_amount: Optional[float] = 0.0
    claim_paid_amount: Optional[float] = 0.0
    deductible_amount: Optional[float] = 0.0
    outstanding: Optional[float] = 0.0

    # Step 2
    claim_type: str
    branch: str
    incident_date_time: str
    incident_place: str
    current_location: str
    circumstances: str
    missing_parts_details: str
    workshop_type: str
    vehicle_type: str
    workshop_name: str
    vehicle_availability: str
    date_field: str

    # Step 3
    relation_with_insured: str
    contact_person_name: str
    contact_number: str
    email: EmailStr
    remarks: Optional[str]
    remarks2: Optional[str]
    date_time: str

# ✅ Date normalization function
def normalize_date(date_str):
    try:
        if "/" in date_str:
            day, month, year = date_str.split("/")[:3]
            return f"{year}-{month.zfill(2)}-{day.zfill(2)}"
        return date_str  # Assume already in correct format
    except:
        return date_str

"""#post for claims"""

# ✅ POST endpoint
@app.post("/api/claims")
def submit_claim(claim: Claim):
    try:
        conn = sqlite3.connect(DB_PATH)
        cursor = conn.cursor()

        # Normalize date fields
        def safe(date):
            return normalize_date(date) if date else None

        cursor.execute("""
            INSERT INTO claims (
                policy_no, vehicle_make, vehicle_model, vehicle_color,
                engine_no, chassis_no, registration_no, year_of_manufacture,
                policy_start_date, policy_end_date, vehicle_start_date, vehicle_end_date,
                claim_count, claim_intimation_amount, claim_paid_amount,
                deductible_amount, outstanding,

                claim_type, branch, incident_date_time, incident_place, current_location,
                circumstances, missing_parts_details, workshop_type, vehicle_type,
                workshop_name, vehicle_availability, date_field,

                relation_with_insured, contact_person_name, contact_number,
                email, remarks, remarks2, date_time
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """, (
            claim.policy_no, claim.vehicle_make, claim.vehicle_model, claim.vehicle_color,
            claim.engine_no, claim.chassis_no, claim.registration_no, claim.year_of_manufacture,
            safe(claim.policy_start_date), safe(claim.policy_end_date), safe(claim.vehicle_start_date), safe(claim.vehicle_end_date),
            claim.claim_count, claim.claim_intimation_amount, claim.claim_paid_amount,
            claim.deductible_amount, claim.outstanding,

            claim.claim_type, claim.branch, claim.incident_date_time, claim.incident_place, claim.current_location,
            claim.circumstances, claim.missing_parts_details, claim.workshop_type, claim.vehicle_type,
            claim.workshop_name, claim.vehicle_availability, safe(claim.date_field),

            claim.relation_with_insured, claim.contact_person_name, claim.contact_number,
            claim.email, claim.remarks, claim.remarks2, safe(claim.date_time)
        ))
        conn.commit()
        return {"message": "✅ Full claim saved successfully!"}

    except Exception as e:
        raise HTTPException(status_code=500, detail=f"❌ Submission failed: {str(e)}")

    finally:
        conn.close()

"""#main file for damage, severity and cost"""

# main.py
import os, uuid, base64, traceback
import numpy as np
import cv2
import joblib
import torch
import pandas as pd
from fastapi import FastAPI, UploadFile, File, Form
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from detectron2.engine import DefaultPredictor
from detectron2.config import get_cfg
from detectron2 import model_zoo
from detectron2.data import MetadataCatalog
from detectron2.utils.visualizer import Visualizer
from torchvision.ops import box_iou
from fastapi.staticfiles import StaticFiles

from torchvision.ops import nms


# # === CORS ===
# app = FastAPI(title="Car Damage Estimator API")
# app.add_middleware(
#     CORSMiddleware,
#     allow_origins=["http://localhost:8080"],
#     # allow_origins=["*"] , # Only for development
#     allow_credentials=True,
#     allow_methods=["*"],
#     allow_headers=["*"],
# )



UPLOAD_DIR = "/content/uploads"
os.makedirs(UPLOAD_DIR, exist_ok=True)


# ✅ Expose uploaded images so they can be served via /uploads/...
app.mount("/uploads", StaticFiles(directory=UPLOAD_DIR), name="uploads")

# === Load ML models ===
model = joblib.load("/content/drive/MyDrive/repair_model_severe/repair_cost_model.pkl")
encoder = joblib.load("/content/drive/MyDrive/repair_model_severe/car_model_encoder.pkl")

# --- Car repair configs ---
all_parts = [
    "RunningBoard-Dent", "Sidemirror-Damage", "damaged-head-light",
    "damaged-hood", "damaged_bumper", "damaged_door", "damaged_fender",
    "damaged_trunk", "missing_grille", "shattered-glass"
]

base_costs = {
    'RunningBoard-Dent': 6000, 'Sidemirror-Damage': 4500, 'damaged-head-light': 7000,
    'damaged-hood': 12000, 'damaged_bumper': 14000, 'damaged_door': 16000,
    'damaged_fender': 10000, 'damaged_trunk': 10000, 'missing_grille': 6000, 'shattered-glass': 9000
}

severity_multipliers = {'minor': 1.0, 'moderate': 1.5, 'severe': 2.2}
severity_map = {"none": 0, "minor": 1, "moderate": 2, "severe": 3}

car_cost_groups  = {
    "economy": {
        "models": [
            "Suzuki Mehran", "Suzuki Alto", "Suzuki Cultus", "Daihatsu Mira", "FAW V2", "Suzuki Every", "Maruti Suzuki Wagon R",
            "Prince Pearl", "United Bravo", "Chery QQ", "Hyundai Santro", "Nissan Dayz", "Honda N-One", "Mitsubishi Ek Wagon",
            "Suzuki Wagon R", "Toyota Passo", "Daihatsu Move", "Mazda Carol", "Subaru Pleo", "Toyota Pixis", "Suzuki Lapin",
            "Honda Life", "Mitsubishi Minicab", "Daihatsu Hijet", "Suzuki Bolan", "Suzuki Ravi", "Mazda Scrum", "Honda Today",
            "Toyota Duet", "Hyundai Excel", "Chevrolet Joy", "Suzuki Khyber", "Suzuki FX", "Honda Zest", "Mazda Flair",
            "Subaru Stella", "Mitsubishi Toppo", "Nissan Otti", "Daihatsu Esse", "Suzuki MR Wagon", "Honda Vamos",
            "Toyota Pixis Epoch", "Nissan Roox", "Daihatsu Copen"
        ],
        "multiplier": 0.6,
        "labor_paint": 4000
    },
    "mid": {
        "models": [
            "Honda City", "Toyota Corolla", "Toyota Corolla XLI/GLI", "Toyota Prius", "Toyota Vitz", "Toyota Yaris",
            "Changan Alsvin", "Honda Civic", "Nissan Sunny", "Suzuki Liana", "Hyundai Verna", "Kia Rio", "Chevrolet Optra",
            "Proton Saga", "Peugeot 2008", "Mitsubishi Lancer", "Renault Logan", "Toyota Belta", "Daihatsu Terios",
            "Toyota Sienta", "Honda Fit", "Honda Grace", "Mazda Axela", "Suzuki Ciaz", "Geely Emgrand", "Chery Arrizo",
            "BYD F3", "DFSK Glory 580", "Toyota Platz", "Toyota Aqua", "Nissan Tiida", "Honda Airwave", "Suzuki Baleno",
            "Mitsubishi Mirage", "Mazda Demio", "Chevrolet Cruze", "Hyundai Accent", "Renault Megane", "Toyota Axio",
            "Nissan Bluebird", "Hyundai Elantra GL", "Mazda Familia"
        ],
        "multiplier": 1.0,
        "labor_paint": 6000
    },
    "premium": {
        "models": [
            "Hyundai Elantra", "Kia Sportage", "Hyundai Tucson", "Toyota Fortuner", "Toyota Camry", "MG HS", "Honda Accord",
            "Mazda CX-5", "Nissan X-Trail", "Subaru Forester", "BMW 3 Series", "Audi A4", "Mercedes C-Class", "Lexus NX",
            "Changan Oshan X7", "DFSK Glory 580 Pro", "Proton X70", "MG ZS EV", "Peugeot 3008", "Kia Sorento", "Hyundai Sonata",
            "Toyota Crown", "Toyota Land Cruiser", "Hyundai Palisade", "Range Rover Evoque", "Audi Q3", "Honda CR-V",
            "Mitsubishi Outlander", "Volvo XC60", "Suzuki Vitara", "Audi A6", "Mercedes E-Class", "BMW 5 Series",
            "Lexus RX", "Toyota Prado", "Porsche Macan", "Land Rover Discovery", "Jaguar XE", "Genesis G70", "Volvo XC90",
            "Porsche Cayenne", "BMW X1", "Mercedes GLA", "Tesla Model 3", "Audi e-tron"
        ],
        "multiplier": 1.8,
        "labor_paint": 8000
    }
}
# ✅ Correct get_group_info function
def get_group_info(car_model):
    for group in car_cost_groups.values():
        if car_model in group["models"]:
            return group
    return {"multiplier": 1.0, "labor_paint": 6000}  # Fallback

# === Load Detectron2 models ===
def load_predictor(weight_path, num_classes):
    cfg = get_cfg()
    cfg.merge_from_file(model_zoo.get_config_file(
        "COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"))
    cfg.MODEL.WEIGHTS = weight_path
    cfg.MODEL.ROI_HEADS.NUM_CLASSES = num_classes
    cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5
    cfg.MODEL.DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
    return DefaultPredictor(cfg)

predictor_parts = load_predictor("/content/drive/MyDrive/damage_model.pth", 11)
predictor_sev = load_predictor("/content/drive/MyDrive/severity_model.pth", 3)

metadata_parts = MetadataCatalog.get("car_part_val")
metadata_parts.thing_classes = [
    'car', 'RunningBoard-Dent', 'Sidemirror-Damage', 'damaged-head-light',
    'damaged-hood', 'damaged_bumper', 'damaged_door', 'damaged_fender',
    'damaged_trunk', 'missing_grille', 'shattered-glass'
]

metadata_sev = MetadataCatalog.get("car_severity_val")
metadata_sev.thing_classes = ["minor", "moderate", "severe"]

# === Helper ===
def encode_img(img_np):
    _, buffer = cv2.imencode(".jpg", img_np)
    return base64.b64encode(buffer).decode("utf-8")


# === Core Inference Function ===
def filter_top_by_class(instances):
    if len(instances) == 0:
        return instances
    selected = []
    boxes = instances.pred_boxes.tensor
    scores = instances.scores
    classes = instances.pred_classes
    by_class = defaultdict(list)
    for idx, cls in enumerate(classes):
        by_class[int(cls)].append(idx)
    for cls, idxs in by_class.items():
        cls_boxes = boxes[idxs]
        cls_scores = scores[idxs]
        keep = nms(cls_boxes, cls_scores, 0.5)
        if keep.numel() > 0:
            best_idx = idxs[keep[cls_scores[keep].argmax()].item()]
            selected.append(best_idx)
    return instances[selected] if selected else instances[[]]

def detect_and_estimate_cost(image_path, car_model):
    img = cv2.imread(image_path)
    if img is None:
        raise FileNotFoundError(f"Could not load image: {image_path}")
    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    part_outputs = predictor_parts(img)
    severity_outputs = predictor_sev(img)
    part_instances = filter_top_by_class(part_outputs["instances"].to("cpu"))
    all_sev_instances = severity_outputs["instances"].to("cpu")
    if len(all_sev_instances) > 0:
        top_idx = all_sev_instances.scores.argmax().item()
        severity_instances = all_sev_instances[top_idx:top_idx+1]

    else:
        severity_instances = all_sev_instances
    part_boxes = part_instances.pred_boxes.tensor if part_instances.has("pred_boxes") else []
    part_classes = part_instances.pred_classes.tolist()
    part_scores = part_instances.scores.tolist() if part_instances.has("scores") else [1.0] * len(part_classes)
    sev_boxes = severity_instances.pred_boxes.tensor if severity_instances.has("pred_boxes") else []
    sev_classes = severity_instances.pred_classes.tolist()
    matched = {}
    if len(part_boxes):
        iou = box_iou(part_boxes, sev_boxes) if len(sev_boxes) else None
        for i, part_cls in enumerate(part_classes):
            part_name = metadata_parts.thing_classes[part_cls]
            if part_name == "car":
                continue
            score = part_scores[i]
            severity = "moderate"
            if iou is not None and len(sev_classes):
                best_match = iou[i].argmax().item()
                if iou[i][best_match] > 0.5:
                    severity = metadata_sev.thing_classes[sev_classes[best_match]]
            if (part_name not in matched) or (matched[part_name][2] < score):
                matched[part_name] = (part_name, severity, score)
    if not matched and part_classes and sev_classes:
        part_name = metadata_parts.thing_classes[part_classes[0]]
        sev = metadata_sev.thing_classes[sev_classes[0]]
        if part_name != "car":
            matched[part_name] = (part_name, sev, 1.0)
    matched = [(p, s) for p, s, _ in matched.values()]
    row = {p: "none" for p in all_parts}
    for part, severity in matched:
        row[part] = severity
    row["car_model"] = car_model
    for part in all_parts:
        row[part] = severity_map.get(row[part], 0)
    input_df = pd.DataFrame([row])
    encoded_model = encoder.transform(input_df[["car_model"]])
    encoded_df = pd.DataFrame(encoded_model, columns=encoder.get_feature_names_out(["car_model"]))
    info = get_group_info(car_model)
    input_df["labor_paint"] = info["labor_paint"]
    input_df["num_damaged_parts"] = sum([1 for p in all_parts if row[p] > 0])
    input_df["severity_score"] = sum([row[p] for p in all_parts])
    X_input = pd.concat([
        input_df[all_parts],
        encoded_df,
        input_df[["labor_paint", "num_damaged_parts", "severity_score"]]
    ], axis=1)
    predicted_cost = float(model.predict(X_input)[0])
    manual_total = 0
    breakdown = []
    for part, severity in matched:
        base = base_costs.get(part, 10000)
        sev_mult = severity_multipliers.get(severity, 1.0)
        total = base * sev_mult * info["multiplier"] + info["labor_paint"]
        breakdown.append({
            "part": part, "severity": severity, "base": int(base),
            "mult": float(sev_mult), "labor": int(info["labor_paint"]), "total": float(total)
        })
        manual_total += total
    out_part = Visualizer(img_rgb.copy(), metadata=metadata_parts, scale=1.0).draw_instance_predictions(part_instances)
    out_sev = Visualizer(img_rgb.copy(), metadata=metadata_sev, scale=1.0).draw_instance_predictions(severity_instances)
    return {
        "predicted_cost": predicted_cost,
        "manual_cost": manual_total,
        "car_model": car_model,
        "damages": breakdown,
        "part_image_base64": encode_img(out_part.get_image()[:, :, ::-1]),
        "severity_image_base64": encode_img(out_sev.get_image()[:, :, ::-1])
    }

"""#post for car damage"""

@app.post("/predict")
async def predict(image: UploadFile = File(...), car_model: str = Form(...)):
    try:
        prediction_id = uuid.uuid4().hex
        save_path = os.path.join(UPLOAD_DIR, f"{prediction_id}_{image.filename}")
        with open(save_path, "wb") as f:
            f.write(await image.read())

        result = detect_and_estimate_cost(save_path, car_model)

        timestamp = datetime.now().isoformat()

        img_parts_path = os.path.join(UPLOAD_DIR, f"{prediction_id}_parts.jpg")
        img_severity_path = os.path.join(UPLOAD_DIR, f"{prediction_id}_severity.jpg")

        with open(img_parts_path, "wb") as f:
            f.write(base64.b64decode(result["part_image_base64"]))
        with open(img_severity_path, "wb") as f:
            f.write(base64.b64decode(result["severity_image_base64"]))

        # ✅ Open fresh DB connection
        with sqlite3.connect(DB_PATH) as conn:
            cursor = conn.cursor()
            cursor.execute("""
                INSERT INTO predictions (
                    id, filename, car_model, predicted_cost, manual_cost,
                    breakdown_json, img_parts_path, img_severity_path, timestamp
                )
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
            """, (
                prediction_id,
                os.path.basename(save_path),
                result["car_model"],
                result["predicted_cost"],
                result["manual_cost"],
                json.dumps(result["damages"]),
                img_parts_path,
                img_severity_path,
                timestamp
            ))
            conn.commit()

        return result

    except Exception as e:
        print("❌ ERROR:", traceback.format_exc())
        return JSONResponse(status_code=500, content={"error": str(e)})


    except Exception as e:
        print("❌ ERROR:", traceback.format_exc())
        return JSONResponse(status_code=500, content={"error": str(e)})
from fastapi.responses import JSONResponse
@app.get("/api/history")
def get_history():
    try:
        with sqlite3.connect(DB_PATH) as conn:
            cursor = conn.cursor()
            cursor.execute("""
                SELECT id, car_model, predicted_cost, manual_cost,
                    img_parts_path, img_severity_path, timestamp
                FROM predictions ORDER BY timestamp DESC
            """)
            rows = cursor.fetchall()

        response = []
        for row in rows:
            prediction_id, model, pred_cost, man_cost, parts_img, sev_img, ts = row
            parts_url = "/uploads/" + os.path.basename(parts_img)
            severity_url = "/uploads/" + os.path.basename(sev_img)

            response.append({
                "id": prediction_id,
                "car_model": model,
                "predicted_cost": int(pred_cost),
                "manual_cost": int(man_cost),
                "timestamp": ts,
                "part_image_url": parts_url,
                "severity_image_url": severity_url
            })

        return JSONResponse(content=response)

    except Exception as e:
        return JSONResponse(status_code=500, content={"error": str(e)})

from typing import List
from pydantic import BaseModel

class ClaimOut(BaseModel):
    id: int
    claim_number: str
    contact_person_name: str
    date_time: str
    claim_paid_amount: float

class ClaimListResponse(BaseModel):
    total: int
    claims: List[ClaimOut]

"""#get for claims"""

from fastapi import APIRouter
from fastapi.responses import JSONResponse

@app.get("/api/claims", response_model=ClaimListResponse)
def get_claims():
    with sqlite3.connect(DB_PATH) as conn:
        conn.row_factory = sqlite3.Row
        cursor = conn.cursor()
        cursor.execute("SELECT * FROM claims ORDER BY id DESC")
        rows = cursor.fetchall()

    claims = []
    for row in rows:
        claim = dict(row)
        claim["claim_number"] = f"CLM-{claim['id']:03d}"
        claims.append({
            "id": claim["id"],
            "claim_number": claim["claim_number"],
            "contact_person_name": claim["contact_person_name"],
            "date_time": claim["date_time"],
            "claim_paid_amount": claim["claim_paid_amount"]
        })

    return {"total": len(claims), "claims": claims}

!ngrok config add-authtoken 2w60MsSu369aNfMm9iGfxVmNgAa_5FVaLeSSjXXby8zuaVj1B

!ngrok config 2vLRvPjHJCPqVJuRNGNd9v0UYQU_7ggjdxxBmB9SkS9UD9R6c

from pyngrok import ngrok
import nest_asyncio
import uvicorn

nest_asyncio.apply()

# Start ngrok tunnel
public_url = ngrok.connect(8000)
print(f"🚀 Public URL: {public_url}/docs")

# Start FastAPI
uvicorn.run(app, host="0.0.0.0", port=8000)

from fastapi.staticfiles import StaticFiles

app = FastAPI()

# Ensure UPLOAD_DIR is defined and exists
UPLOAD_DIR = "/content/uploads"
os.makedirs(UPLOAD_DIR, exist_ok=True)

# Mount the static files directory
app.mount("/uploads", StaticFiles(directory=UPLOAD_DIR), name="uploads")

from fastapi import FastAPI
from fastapi.staticfiles import StaticFiles
import os

app = FastAPI()

UPLOAD_DIR = "/content/uploads"
os.makedirs(UPLOAD_DIR, exist_ok=True)

# Mount the uploads directory
app.mount("/uploads", StaticFiles(directory=UPLOAD_DIR), name="uploads")

from collections import defaultdict

from pyngrok import ngrok
import nest_asyncio
import uvicorn

# Enable nested event loop for Colab
nest_asyncio.apply()

# Set your real authtoken here
ngrok.set_auth_token("2w60MsSu369aNfMm9iGfxVmNgAa_5FVaLeSSjXXby8zuaVj1B")

# Start tunnel
public_url = ngrok.connect(8000)
print(f"🚀 API running at: {public_url}/docs")

# Run the FastAPI server
uvicorn.run(app, host="0.0.0.0", port=8000)
# https://0320-34-124-139-137.ngrok-free.app/

conn = sqlite3.connect(DB_PATH)
cursor = conn.cursor()
# do your SQL operations...
conn.commit()
conn.close()

from fastapi import FastAPI
from pyngrok import ngrok
import nest_asyncio
import uvicorn

app = FastAPI()

@app.get("/")
def read_root():
    return {"message": "FastAPI is working!"}

nest_asyncio.apply()
ngrok.set_auth_token("2vLRvPjHJCPqVJuRNGNd9v0UYQU_7ggjdxxBmB9SkS9UD9R6c")  # ✅ Use your token

public_url = ngrok.connect(8000)
print(f"🚀 API running at: {public_url}/docs")

uvicorn.run(app, host="0.0.0.0", port=8000)

from pyngrok import ngrok
import nest_asyncio
import uvicorn

nest_asyncio.apply()

# Start ngrok tunnel
public_url = ngrok.connect(8000)
print(f"🚀 Public URL: {public_url}/docs")

# Start FastAPI
uvicorn.run(app, host="0.0.0.0", port=8000)

!ngrok config add-authtoken 2XgUIC1VsN2JSCgOxcRhA54UL2u_3HFN8D7xEHQaD8oyGuCX4

# from pyngrok import ngrok

# ngrok.set_auth_token("2XgUIC1VsN2JSCgOxcRhA54UL2u_3HFN8D7xEHQaD8oyGuCX4")
# public_url = ngrok.connect(8000)
# print("Public URL:", public_url)

from pyngrok import ngrok

ngrok.kill()  # This will kill all active tunnels

# !pkill -f ngrok